# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crccloud', '0002_client_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created date', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated date', null=True)),
                ('topic', models.CharField(blank=True, help_text='Potential name of the project', max_length=200, null=True)),
                ('recruitment_duration', models.CharField(blank=True, help_text='Recruitment duration', max_length=50, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency for this BID', max_length=5, null=True)),
                ('project_mngt_cost', models.FloatField(blank=True, help_text='Project management cost', null=True)),
                ('incentive_handling_unit_cost', models.FloatField(blank=True, help_text='Incentive handling unit cost', null=True)),
                ('incentive_handling_qte', models.FloatField(blank=True, help_text='Incentive handling quantity', null=True)),
                ('catering_client', models.IntegerField(blank=True, help_text='Catering for the client', null=True)),
                ('refreshments_respondent_unit_cost', models.FloatField(blank=True, help_text='Refreshment unit cost', null=True)),
                ('refreshments_respondent_qte', models.FloatField(blank=True, help_text='Refreshment quantity', null=True)),
                ('moderation_unit_cost', models.FloatField(blank=True, help_text='Moderation unit cost', null=True)),
                ('moderation_qte', models.FloatField(blank=True, help_text='Moderation quantity', null=True)),
                ('moderator_briefing', models.IntegerField(blank=True, help_text='Moderator briefing', null=True)),
                ('moderator_travel', models.IntegerField(blank=True, help_text='Moderator travel', null=True)),
                ('simultaneous_translation', models.IntegerField(blank=True, help_text='Simultaneous translator', null=True)),
                ('translation_words', models.IntegerField(blank=True, help_text='Estimation of words to translate', null=True)),
                ('translation_cost', models.IntegerField(blank=True, help_text='Translation cost', null=True)),
                ('facility_duration', models.CharField(blank=True, help_text='Facility rental duration', max_length=50, null=True)),
                ('facility_rental_unit_cost', models.FloatField(blank=True, help_text='Facility rental unit cost', null=True)),
                ('facility_rental_qte', models.FloatField(blank=True, help_text='Facility rental quantity', null=True)),
                ('notes', models.CharField(blank=True, help_text='Notes', max_length=300, null=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client for this BID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_client', to='crccloud.Client')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
