# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crccloud', '0003_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='catering_client',
            field=models.FloatField(blank=True, help_text='Catering for the client', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='moderator_briefing',
            field=models.FloatField(blank=True, help_text='Moderator briefing', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='moderator_travel',
            field=models.FloatField(blank=True, help_text='Moderator travel', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='simultaneous_translation',
            field=models.FloatField(blank=True, help_text='Simultaneous translator', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='translation_cost',
            field=models.FloatField(blank=True, help_text='Translation cost', null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='translation_words',
            field=models.FloatField(blank=True, help_text='Estimation of words to translate', null=True),
        ),
    ]
