# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crccloud', '0004_auto_20171020_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created date', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated date', null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the deliverables', max_length=200, null=True)),
                ('unit_cost', models.FloatField(blank=True, help_text='Unit cost', null=True)),
                ('quantity', models.FloatField(blank=True, help_text='Quantity', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Duration', null=True)),
                ('bid', models.ForeignKey(help_text='Deliverable for this BID', on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_bid', to='crccloud.Bid')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created date', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated date', null=True)),
                ('name', models.CharField(blank=True, help_text='Name of the test', max_length=200, null=True)),
                ('duration', models.CharField(blank=True, help_text='Duration of the test', max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Start date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Start date', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Created date', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated date', null=True)),
                ('city', models.CharField(blank=True, help_text='Location of the test', max_length=200, null=True)),
                ('type_respondent', models.CharField(blank=True, help_text='Type of respondent', max_length=200, null=True)),
                ('nbr_respondent', models.FloatField(blank=True, help_text='Number of respondent(s)', null=True)),
                ('over_recruitment', models.FloatField(blank=True, help_text='Over recruitment', null=True)),
                ('language', models.CharField(blank=True, help_text='Language of test', max_length=20, null=True)),
                ('incentive', models.FloatField(blank=True, help_text='Incentive per respondent', null=True)),
                ('recruitment_cost', models.FloatField(blank=True, help_text='Recruitment cost per respondent', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True)),
                ('bid', models.ForeignKey(help_text='Infos linked to this project', on_delete=django.db.models.deletion.CASCADE, related_name='info_bid', to='crccloud.Bid')),
                ('created_by', models.ForeignKey(blank=True, help_text='Creator', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='methodology',
            name='respondent',
            field=models.ForeignKey(help_text='Methodology linked to this respondent group', on_delete=django.db.models.deletion.CASCADE, related_name='methodology_respondent', to='crccloud.Respondent'),
        ),
    ]
