# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crccloud', '0005_auto_20171020_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverables',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True),
        ),
    ]
