# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crccloud', '0006_deliverables_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverables',
            name='bid',
            field=models.ForeignKey(help_text='Deliverables linked to this BID', on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_bid', to='crccloud.Bid'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='bid',
            field=models.ForeignKey(help_text='Respondent group attached to this BID', on_delete=django.db.models.deletion.CASCADE, related_name='info_bid', to='crccloud.Bid'),
        ),
    ]
