# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crccloud', '0007_auto_20171020_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deliverables',
            new_name='Deliverable',
        ),
    ]
