# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crccloud', '0010_auto_20171023_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='incentive_total',
            field=models.FloatField(blank=True, help_text='Incentive total', null=True),
        ),
        migrations.AddField(
            model_name='respondent',
            name='recruitment_total',
            field=models.FloatField(blank=True, help_text='Recruitment total', null=True),
        ),
    ]
